<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHQOWSyZ\App_KernelProdContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHQOWSyZ/App_KernelProdContainer.php') {
    touch(__DIR__.'/ContainerHQOWSyZ.legacy');

    return;
}

if (!\class_exists(App_KernelProdContainer::class, false)) {
    \class_alias(\ContainerHQOWSyZ\App_KernelProdContainer::class, App_KernelProdContainer::class, false);
}

return new \ContainerHQOWSyZ\App_KernelProdContainer([
    'container.build_hash' => 'HQOWSyZ',
    'container.build_id' => 'f5582068',
    'container.build_time' => 1612759657,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHQOWSyZ');
