<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'getTasks' => [[], ['_controller' => 'App\\Controller\\TaskController::getTasks'], [], [['text', '/tasks']], [], []],
    'create' => [[], ['_controller' => 'App\\Controller\\TaskController::create'], [], [['text', '/create']], [], []],
    'edit' => [['id'], ['_controller' => 'App\\Controller\\TaskController::edit'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/edit']], [], []],
    'delete' => [['id'], ['_controller' => 'App\\Controller\\TaskController::delete'], [], [['variable', '/', '[^/]++', 'id', true], ['text', '/delete']], [], []],
    'register' => [[], ['_controller' => 'App\\Controller\\UserController::register'], [], [['text', '/register']], [], []],
    'login' => [[], ['_controller' => 'App\\Controller\\UserController::login'], [], [['text', '/']], [], []],
    'logout' => [[], [], [], [['text', '/logout']], [], []],
];
