<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerWjwoEsW\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerWjwoEsW/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerWjwoEsW.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerWjwoEsW\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerWjwoEsW\App_KernelDevDebugContainer([
    'container.build_hash' => 'WjwoEsW',
    'container.build_id' => '3ed57e06',
    'container.build_time' => 1612761907,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerWjwoEsW');
